/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 31 generated on 2011-02-17 16:25:14.357977
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object:
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -shared -Wl,-soname,ik.so -o ik.so ik.cpp
#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifdef BOOST_ASSERT
#define IKFAST_ASSERT BOOST_ASSERT
#else

#include <stdexcept>
#include <sstream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  6.28318530717959
#define IKPI  3.14159265358979
#define IKPI_2  1.57079632679490

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#endif // _MSC_VER

// defined when creating a shared object/dll
#ifdef IKFAST_CLIBRARY
#ifdef _MSC_VER
#define IKFAST_API extern "C" __declspec(dllexport)
#else
#define IKFAST_API extern "C"
#endif
#else
#define IKFAST_API
#endif

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

typedef double IKReal;
class IKSolution
{
public:
    /// Gets a solution given its free parameters
    /// \param pfree The free parameters required, range is in [-pi,pi]
    void GetSolution(IKReal* psolution, const IKReal* pfree) const {
        for(size_t i = 0; i < basesol.size(); ++i) {
            if( basesol[i].freeind < 0 )
                psolution[i] = basesol[i].foffset;
            else {
                IKFAST_ASSERT(pfree != NULL);
                psolution[i] = pfree[basesol[i].freeind]*basesol[i].fmul + basesol[i].foffset;
                if( psolution[i] > IKPI ) {
                    psolution[i] -= IK2PI;
                }
                else if( psolution[i] < -IKPI ) {
                    psolution[i] += IK2PI;
                }
            }
        }
    }

    /// Gets the free parameters the solution requires to be set before a full solution can be returned
    /// \return vector of indices indicating the free parameters
    const std::vector<int>& GetFree() const { return vfree; }

    struct VARIABLE
    {
        VARIABLE() : freeind(-1), fmul(0), foffset(0) {}
        VARIABLE(int freeind, IKReal fmul, IKReal foffset) : freeind(freeind), fmul(fmul), foffset(foffset) {}
        int freeind;
        IKReal fmul, foffset; ///< joint value is fmul*sol[freeind]+foffset
    };

    std::vector<VARIABLE> basesol;       ///< solution and their offsets if joints are mimiced
    std::vector<int> vfree;
};

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1.001f && f < 1.001f ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1.001 && f < 1.001 ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline float IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1.001f && f < 1.001f ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0.0f;
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1.001 && f < 1.001 ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0.0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) )
        return 0;
    return atan2f(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) )
        return 0;
    return atan2(fy,fx);
}

IKFAST_API int getNumFreeParameters() { return 1; }
IKFAST_API int* getFreeParameters() { static int freeparams[] = {2}; return freeparams; }
IKFAST_API int getNumJoints() { return 7; }

IKFAST_API int getIKRealSize() { return sizeof(IKReal); }

IKFAST_API int getIKType() { return 0x67000001; }

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void fk(const IKReal* j, IKReal* eetrans, IKReal* eerot) {
IKReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70;
x0=IKsin(j[1]);
x1=IKcos(j[2]);
x2=IKsin(j[3]);
x3=IKcos(j[1]);
x4=IKcos(j[3]);
x5=IKcos(j[4]);
x6=IKsin(j[2]);
x7=IKsin(j[4]);
x8=((x2)*(x3));
x9=((x0)*(x1)*(x4));
x10=((x9)+(x8));
x11=((-1.00000000000000)*(x10));
x12=IKcos(j[6]);
x13=((x0)*(x5)*(x6));
x14=IKsin(j[6]);
x15=IKcos(j[5]);
x16=((x0)*(x6)*(x7));
x17=((x11)*(x5));
x18=((x17)+(x16));
x19=((x15)*(x18));
x20=IKsin(j[5]);
x21=((x0)*(x1)*(x2));
x22=((x3)*(x4));
x23=((((-1.00000000000000)*(x22)))+(x21));
x24=((x20)*(x23));
x25=((x19)+(x24));
x26=IKcos(j[0]);
x27=IKsin(j[0]);
x28=((x26)*(x6));
x29=((x1)*(x27)*(x3));
x30=((x28)+(x29));
x31=((-1.00000000000000)*(x30));
x32=((x31)*(x4));
x33=((x0)*(x2)*(x27));
x34=((x33)+(x32));
x35=((x27)*(x3)*(x6));
x36=((x1)*(x26));
x37=((((-1.00000000000000)*(x36)))+(x35));
x38=((x37)*(x5));
x39=((x34)*(x7));
x40=((((-1.00000000000000)*(x39)))+(x38));
x41=((x0)*(x27)*(x4));
x42=((-1.00000000000000)*(x2)*(x31));
x43=((x42)+(x41));
x44=((x20)*(x43));
x45=((x34)*(x5));
x46=((x37)*(x7));
x47=((x46)+(x45));
x48=((x15)*(x47));
x49=((x48)+(x44));
x50=((x27)*(x6));
x51=((x3)*(x36));
x52=((x50)+(((-1.00000000000000)*(x51))));
x53=((x1)*(x27));
x54=((x28)*(x3));
x55=((x54)+(x53));
x56=((x0)*(x2)*(x26));
x57=((x4)*(x52));
x58=((x57)+(x56));
x59=((x0)*(x26)*(x4));
x60=((-1.00000000000000)*(x2)*(x52));
x61=((x59)+(x60));
x62=((x20)*(x61));
x63=((x5)*(x58));
x64=((x55)*(x7));
x65=((x63)+(x64));
x66=((x15)*(x65));
x67=((x62)+(x66));
x68=((x5)*(x55));
x69=((-1.00000000000000)*(x58)*(x7));
x70=((x68)+(x69));
eerot[0]=((((x14)*(((((-1.00000000000000)*(x11)*(x7)))+(x13)))))+(((x12)*(x25))));
eerot[1]=((((x12)*(((((-1.00000000000000)*(x11)*(x7)))+(x13)))))+(((-1.00000000000000)*(x14)*(x25))));
eerot[2]=((((x18)*(x20)))+(((-1.00000000000000)*(x15)*(x23))));
eetrans[0]=((0.0790000000000000)+(((0.300000000000000)*(x22)))+(((-0.300000000000000)*(x21)))+(((-0.0450000000000000)*(x0)*(x1)))+(((0.550000000000000)*(x3)))+(((0.0450000000000000)*(x8)))+(((0.0450000000000000)*(x9))));
eerot[3]=((((x14)*(x40)))+(((x12)*(x49))));
eerot[4]=((((x12)*(x40)))+(((-1.00000000000000)*(x14)*(x49))));
eerot[5]=((((x20)*(x47)))+(((-1.00000000000000)*(x15)*(x43))));
eetrans[1]=((0.191000000000000)+(((-0.0450000000000000)*(x29)))+(((-0.0450000000000000)*(x28)))+(((-0.0450000000000000)*(x32)))+(((-0.0450000000000000)*(x33)))+(((0.300000000000000)*(x2)*(x31)))+(((-0.550000000000000)*(x0)*(x27)))+(((-0.300000000000000)*(x41))));
eerot[6]=((((-1.00000000000000)*(x12)*(x67)))+(((-1.00000000000000)*(x14)*(x70))));
eerot[7]=((((x14)*(x67)))+(((-1.00000000000000)*(x12)*(x70))));
eerot[8]=((((x15)*(x61)))+(((-1.00000000000000)*(x20)*(x65))));
eetrans[2]=((0.905000000000000)+(((0.300000000000000)*(x59)))+(((0.550000000000000)*(x0)*(x26)))+(((-0.0450000000000000)*(x50)))+(((-0.300000000000000)*(x2)*(x52)))+(((0.0450000000000000)*(x51)))+(((0.0450000000000000)*(x56)))+(((0.0450000000000000)*(x57))));
}

class IKSolver {
public:
IKReal j11, cj11, sj11,
j12, cj12, sj12,
j14, cj14, sj14,
j15, cj15, sj15,
j16, cj16, sj16,
j17, cj17, sj17,
j13, cj13, sj13,
new_r00, r00, rxp0_0,
new_r01, r01, rxp0_1,
new_r02, r02, rxp0_2,
new_r10, r10, rxp1_0,
new_r11, r11, rxp1_1,
new_r12, r12, rxp1_2,
new_r20, r20, rxp2_0,
new_r21, r21, rxp2_1,
new_r22, r22, rxp2_2,
new_px, new_py, new_pz, px, py, pz, npx, npy, npz, pp;

bool ik(const IKReal* eetrans, const IKReal* eerot, const IKReal* pfree, std::vector<IKSolution>& vsolutions) {
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
vsolutions.resize(0); vsolutions.reserve(8);
j13=pfree[0]; cj13=cos(pfree[0]); sj13=sin(pfree[0]);
r00 = eerot[0*3+0];
r01 = eerot[0*3+1];
r02 = eerot[0*3+2];
r10 = eerot[1*3+0];
r11 = eerot[1*3+1];
r12 = eerot[1*3+2];
r20 = eerot[2*3+0];
r21 = eerot[2*3+1];
r22 = eerot[2*3+2];
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_r00=((-1.00000000000000)*(r20));
new_r01=((-1.00000000000000)*(r21));
new_r02=((-1.00000000000000)*(r22));
new_px=((0.905000000000000)+(((-1.00000000000000)*(pz))));
new_r10=r10;
new_r11=r11;
new_r12=r12;
new_py=((-0.191000000000000)+(py));
new_r20=r00;
new_r21=r01;
new_r22=r02;
new_pz=((-0.0790000000000000)+(px));
r00 = new_r00; r01 = new_r01; r02 = new_r02; r10 = new_r10; r11 = new_r11; r12 = new_r12; r20 = new_r20; r21 = new_r21; r22 = new_r22; px = new_px; py = new_py; pz = new_pz;
pp=(((px)*(px))+((py)*(py))+((pz)*(pz)));
npx=((((px)*(r00)))+(((py)*(r10)))+(((pz)*(r20))));
npy=((((px)*(r01)))+(((py)*(r11)))+(((pz)*(r21))));
npz=((((px)*(r02)))+(((py)*(r12)))+(((pz)*(r22))));
rxp0_0=((((-1.00000000000000)*(py)*(r20)))+(((pz)*(r10))));
rxp0_1=((((px)*(r20)))+(((-1.00000000000000)*(pz)*(r00))));
rxp0_2=((((-1.00000000000000)*(px)*(r10)))+(((py)*(r00))));
rxp1_0=((((-1.00000000000000)*(py)*(r21)))+(((pz)*(r11))));
rxp1_1=((((px)*(r21)))+(((-1.00000000000000)*(pz)*(r01))));
rxp1_2=((((-1.00000000000000)*(px)*(r11)))+(((py)*(r01))));
rxp2_0=((((-1.00000000000000)*(py)*(r22)))+(((pz)*(r12))));
rxp2_1=((((px)*(r22)))+(((-1.00000000000000)*(pz)*(r02))));
rxp2_2=((((-1.00000000000000)*(px)*(r12)))+(((py)*(r02))));
{
IKReal j14array[2], cj14array[2], sj14array[2];
bool j14valid[2]={false};
IKReal x0=2232.04592246665;
IKReal x1=((0.396550000000000)+(((-1.00000000000000)*(pp))));
IKReal x2=((0.00133814288649598)*(x0)*(x1));
if( (x2) < -1.0001 || (x2) > 1.0001 )
    continue;
IKReal x3=IKasin(x2);
j14array[0]=((-1.34027003705633)+(((-1.00000000000000)*(x3))));
sj14array[0]=IKsin(j14array[0]);
cj14array[0]=IKcos(j14array[0]);
j14array[1]=((1.80132261653346)+(x3));
sj14array[1]=IKsin(j14array[1]);
cj14array[1]=IKcos(j14array[1]);
if( j14array[0] > IKPI )
{
    j14array[0]-=IK2PI;
}
else if( j14array[0] < -IKPI )
{    j14array[0]+=IK2PI;
}
j14valid[0] = true;
if( j14array[1] > IKPI )
{
    j14array[1]-=IK2PI;
}
else if( j14array[1] < -IKPI )
{    j14array[1]+=IK2PI;
}
j14valid[1] = true;
if( j14valid[0] && j14valid[1] && IKabs(cj14array[0]-cj14array[1]) < 0.0001 && IKabs(sj14array[0]-sj14array[1]) < 0.0001 )
{
    j14valid[1]=false;
}
for(int ij14 = 0; ij14 < 2; ++ij14)
{
if( !j14valid[ij14] )
{
    continue;
}
j14 = j14array[ij14]; cj14 = cj14array[ij14]; sj14 = sj14array[ij14];

{
IKReal j11array[2], cj11array[2], sj11array[2];
bool j11valid[2]={false};
IKReal x4=(px)*(px);
IKReal x5=(py)*(py);
IKReal x6=((x5)+(x4));
if( (x6) < (IKReal)-0.00001 )
    continue;
IKReal x7=IKsqrt(x6);
IKReal x8=IKabs(x7);
IKReal x9=((IKabs(x8) != 0)?((IKReal)1/(x8)):(IKReal)1.0e30);
IKReal x10=((0.0450000000000000)*(sj13));
IKReal x11=((0.300000000000000)*(sj13)*(sj14));
IKReal x12=((x11)+(x10));
IKReal x13=((cj14)*(x10));
IKReal x14=((((-1.00000000000000)*(x13)))+(x12));
IKReal x15=((x14)*(x9));
if( (x15) < -1.0001 || (x15) > 1.0001 )
    continue;
IKReal x16=IKasin(x15);
IKReal x17=((-1.00000000000000)*(px));
IKReal x18=IKatan2(py, x17);
j11array[0]=((((-1.00000000000000)*(x18)))+(((-1.00000000000000)*(x16))));
sj11array[0]=IKsin(j11array[0]);
cj11array[0]=IKcos(j11array[0]);
j11array[1]=((3.14159265358979)+(((-1.00000000000000)*(x18)))+(x16));
sj11array[1]=IKsin(j11array[1]);
cj11array[1]=IKcos(j11array[1]);
if( j11array[0] > IKPI )
{
    j11array[0]-=IK2PI;
}
else if( j11array[0] < -IKPI )
{    j11array[0]+=IK2PI;
}
j11valid[0] = true;
if( j11array[1] > IKPI )
{
    j11array[1]-=IK2PI;
}
else if( j11array[1] < -IKPI )
{    j11array[1]+=IK2PI;
}
j11valid[1] = true;
if( j11valid[0] && j11valid[1] && IKabs(cj11array[0]-cj11array[1]) < 0.0001 && IKabs(sj11array[0]-sj11array[1]) < 0.0001 )
{
    j11valid[1]=false;
}
for(int ij11 = 0; ij11 < 2; ++ij11)
{
if( !j11valid[ij11] )
{
    continue;
}
j11 = j11array[ij11]; cj11 = cj11array[ij11]; sj11 = sj11array[ij11];

{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(sj13)*((pz)*(pz))))+(((-1.00000000000000)*(sj13)*((py)*(py))*((sj11)*(sj11))))+(((-2.00000000000000)*(cj11)*(px)*(py)*(sj11)*(sj13)))+(((-1.00000000000000)*(sj13)*((cj11)*(cj11))*((px)*(px)))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x19=((12.2222222222222)*(cj11)*(px));
IKReal x20=((12.2222222222222)*(py)*(sj11));
IKReal x21=((py)*(sj11)*(sj14));
IKReal x22=((cj11)*(px)*(sj14));
IKReal x23=((cj13)*(cj14)*(pz));
IKReal x24=((6.66666666666667)*(cj14)*(py)*(sj11));
IKReal x25=((6.66666666666667)*(cj11)*(cj14)*(px));
IKReal x26=((x19)+(x24)+(x25)+(x20)+(x21)+(x22)+(x23));
IKReal x27=((cj13)*(pz));
IKReal x28=((6.66666666666667)*(sj14)*(x27));
IKReal x29=((x27)+(x28));
IKReal x30=((((-1.00000000000000)*(x29)))+(x26));
dummyeval[0]=x30;
dummyeval[1]=x30;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(cj13)*((py)*(py))*((sj11)*(sj11))))+(((-1.00000000000000)*(cj13)*((cj11)*(cj11))*((px)*(px))))+(((-2.00000000000000)*(cj11)*(cj13)*(px)*(py)*(sj11)))+(((-1.00000000000000)*(cj13)*((pz)*(pz)))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[4];
IKReal x31=((0.300000000000000)*(sj14));
IKReal x32=((cj11)*(py));
IKReal x33=((0.0450000000000000)+(x32)+(x31));
IKReal x34=((px)*(sj11));
IKReal x35=((0.0450000000000000)*(cj14));
IKReal x36=((x35)+(x34));
IKReal x37=((((-1.00000000000000)*(x36)))+(x33));
evalcond[0]=((IKfmod(((-1.57079632679490)+(j13)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=((0.396550000000000)+(((0.325950000000000)*(cj14)))+(((0.0765000000000000)*(sj14)))+(((-1.00000000000000)*(pp))));
evalcond[2]=x37;
evalcond[3]=x37;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x38=((6.66666666666667)*(cj14));
IKReal x39=((12.2222222222222)+(sj14)+(x38));
dummyeval[0]=x39;
dummyeval[1]=x39;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x40=((6.66666666666667)*(cj14));
IKReal x41=((12.2222222222222)+(sj14)+(x40));
dummyeval[0]=x41;
dummyeval[1]=x41;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
dummyeval[0]=((((12.2222222222222)*(cj11)*(px)))+(((12.2222222222222)*(py)*(sj11)))+(((py)*(sj11)*(sj14)))+(((cj11)*(px)*(sj14)))+(((6.66666666666667)*(cj14)*(py)*(sj11)))+(((6.66666666666667)*(cj11)*(cj14)*(px))));
dummyeval[1]=((12.2222222222222)+(((6.66666666666667)*(cj14)))+(sj14));
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x42=((0.0450000000000000)*(sj14));
IKReal x43=((0.300000000000000)*(cj14));
IKReal x44=((0.550000000000000)+(x42)+(x43));
j12array[0]=IKatan2(((((IKabs(((((cj11)*(px)*(x43)))+(((cj11)*(px)*(x42)))+(((0.550000000000000)*(py)*(sj11)))+(((py)*(sj11)*(x43)))+(((py)*(sj11)*(x42)))+(((0.550000000000000)*(cj11)*(px))))) != 0)?((IKReal)1/(((((cj11)*(px)*(x43)))+(((cj11)*(px)*(x42)))+(((0.550000000000000)*(py)*(sj11)))+(((py)*(sj11)*(x43)))+(((py)*(sj11)*(x42)))+(((0.550000000000000)*(cj11)*(px)))))):(IKReal)1.0e30))*(((((-1.00000000000000)*((x44)*(x44))))+((pz)*(pz))))), ((pz)*(((IKabs(x44) != 0)?((IKReal)1/(x44)):(IKReal)1.0e30))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x146=((0.0450000000000000)*(sj14));
IKReal x147=((0.300000000000000)*(cj14));
IKReal x148=((0.550000000000000)+(x146)+(x147));
IKReal x149=((IKabs(x148) != 0)?((IKReal)1/(x148)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x149)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))), ((pz)*(x149)));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x150=((0.0450000000000000)*(sj14));
IKReal x151=((0.300000000000000)*(cj14));
IKReal x152=((0.550000000000000)+(x151)+(x150));
IKReal x153=((IKabs(x152) != 0)?((IKReal)1/(x152)):(IKReal)1.0e30);
j12array[0]=IKatan2(((-1.00000000000000)*(x153)*(((((py)*(sj11)))+(((cj11)*(px)))))), ((pz)*(x153)));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
IKReal x154=((px)*(sj11));
IKReal x155=((0.300000000000000)*(sj14));
IKReal x156=((0.0450000000000000)*(cj14));
IKReal x157=((cj11)*(py));
evalcond[0]=((-3.14159265358979)+(IKfmod(((1.57079632679490)+(j13)+(3.14159265358979)), 6.28318530717959)));
evalcond[1]=((0.396550000000000)+(((0.325950000000000)*(cj14)))+(((0.0765000000000000)*(sj14)))+(((-1.00000000000000)*(pp))));
evalcond[2]=((-0.0450000000000000)+(((-1.00000000000000)*(x154)))+(((-1.00000000000000)*(x155)))+(x157)+(x156));
evalcond[3]=((0.0450000000000000)+(((-1.00000000000000)*(x157)))+(((-1.00000000000000)*(x156)))+(x155)+(x154));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x158=((6.66666666666667)*(cj14));
IKReal x159=((12.2222222222222)+(x158)+(sj14));
dummyeval[0]=x159;
dummyeval[1]=x159;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x160=((6.66666666666667)*(cj14));
IKReal x161=((12.2222222222222)+(x160)+(sj14));
dummyeval[0]=x161;
dummyeval[1]=x161;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
dummyeval[0]=((12.2222222222222)+(((6.66666666666667)*(cj14)))+(sj14));
dummyeval[1]=((((12.2222222222222)*(cj11)*(px)))+(((12.2222222222222)*(py)*(sj11)))+(((py)*(sj11)*(sj14)))+(((cj11)*(px)*(sj14)))+(((6.66666666666667)*(cj14)*(py)*(sj11)))+(((6.66666666666667)*(cj11)*(cj14)*(px))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x162=((py)*(sj11));
IKReal x163=((cj11)*(px));
IKReal x164=((x162)+(x163));
j12array[0]=IKatan2(((-1.00000000000000)*(x164)*(((IKabs(((0.550000000000000)+(((0.0450000000000000)*(sj14)))+(((0.300000000000000)*(cj14))))) != 0)?((IKReal)1/(((0.550000000000000)+(((0.0450000000000000)*(sj14)))+(((0.300000000000000)*(cj14)))))):(IKReal)1.0e30))), ((pz)*(x164)*(((IKabs(((((0.550000000000000)*(x162)))+(((0.550000000000000)*(x163)))+(((0.300000000000000)*(cj14)*(x162)))+(((0.300000000000000)*(cj14)*(x163)))+(((0.0450000000000000)*(sj14)*(x163)))+(((0.0450000000000000)*(sj14)*(x162))))) != 0)?((IKReal)1/(((((0.550000000000000)*(x162)))+(((0.550000000000000)*(x163)))+(((0.300000000000000)*(cj14)*(x162)))+(((0.300000000000000)*(cj14)*(x163)))+(((0.0450000000000000)*(sj14)*(x163)))+(((0.0450000000000000)*(sj14)*(x162)))))):(IKReal)1.0e30))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x165=((0.0450000000000000)*(sj14));
IKReal x166=((0.300000000000000)*(cj14));
IKReal x167=((0.550000000000000)+(x166)+(x165));
IKReal x168=((IKabs(x167) != 0)?((IKReal)1/(x167)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x168)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))), ((pz)*(x168)));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x169=((0.0450000000000000)*(sj14));
IKReal x170=((0.300000000000000)*(cj14));
IKReal x171=((0.550000000000000)+(x170)+(x169));
IKReal x172=((IKabs(x171) != 0)?((IKReal)1/(x171)):(IKReal)1.0e30);
j12array[0]=IKatan2(((-1.00000000000000)*(x172)*(((((py)*(sj11)))+(((cj11)*(px)))))), ((pz)*(x172)));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
IKReal x173=((cj11)*(py));
IKReal x174=((px)*(sj11));
IKReal x175=((((-1.00000000000000)*(x174)))+(x173));
evalcond[0]=((IKfmod(((j13)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=((0.396550000000000)+(((0.325950000000000)*(cj14)))+(((0.0765000000000000)*(sj14)))+(((-1.00000000000000)*(pp))));
evalcond[2]=x175;
evalcond[3]=x175;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*((py)*(py))*((sj11)*(sj11))))+(((-1.00000000000000)*((pz)*(pz))))+(((-2.00000000000000)*(cj11)*(px)*(py)*(sj11)))+(((-1.00000000000000)*((cj11)*(cj11))*((px)*(px)))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x176=((6.66666666666667)*(py)*(sj11)*(sj14));
IKReal x177=((pz)*(sj14));
IKReal x178=((py)*(sj11));
IKReal x179=((6.66666666666667)*(cj14)*(pz));
IKReal x180=((6.66666666666667)*(cj11)*(px)*(sj14));
IKReal x181=((cj11)*(px));
IKReal x182=((12.2222222222222)*(pz));
IKReal x183=((x179)+(x178)+(x177)+(x176)+(x180)+(x181)+(x182));
IKReal x184=((cj14)*(x181));
IKReal x185=((cj14)*(x178));
IKReal x186=((x184)+(x185));
IKReal x187=((((-1.00000000000000)*(x186)))+(x183));
dummyeval[0]=x187;
dummyeval[1]=x187;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x188=((12.2222222222222)*(cj11)*(px));
IKReal x189=((12.2222222222222)*(py)*(sj11));
IKReal x190=((cj14)*(pz));
IKReal x191=((py)*(sj11)*(sj14));
IKReal x192=((cj11)*(px)*(sj14));
IKReal x193=((6.66666666666667)*(cj14)*(py)*(sj11));
IKReal x194=((6.66666666666667)*(cj11)*(cj14)*(px));
IKReal x195=((x193)+(x192)+(x191)+(x190)+(x194)+(x188)+(x189));
IKReal x196=((6.66666666666667)*(pz)*(sj14));
IKReal x197=((x196)+(pz));
IKReal x198=((((-1.00000000000000)*(x197)))+(x195));
dummyeval[0]=x198;
dummyeval[1]=x198;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x199=((0.0450000000000000)*(sj14));
IKReal x200=((0.300000000000000)*(cj14));
IKReal x201=((0.550000000000000)+(x199)+(x200));
IKReal x202=((0.550000000000000)*(py)*(sj11));
IKReal x203=((py)*(sj11)*(x200));
IKReal x204=((cj11)*(px)*(x199));
IKReal x205=((py)*(sj11)*(x199));
IKReal x206=((cj11)*(px)*(x200));
IKReal x207=((0.550000000000000)*(cj11)*(px));
IKReal x208=((0.0450000000000000)*(cj14)*(pz));
IKReal x209=((x207)+(x206)+(x205)+(x204)+(x203)+(x202)+(x208));
IKReal x210=((0.0450000000000000)*(pz));
IKReal x211=((0.300000000000000)*(pz)*(sj14));
IKReal x212=((x210)+(x211));
IKReal x213=((x209)+(((-1.00000000000000)*(x212))));
IKReal x214=((IKabs(x213) != 0)?((IKReal)1/(x213)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x214)*(((((-1.00000000000000)*((x201)*(x201))))+((pz)*(pz))))), ((-1.00000000000000)*(x214)*(((((pz)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))))+(((x201)*(((0.0450000000000000)+(((-0.0450000000000000)*(cj14)))+(((0.300000000000000)*(sj14)))))))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x215=((0.300000000000000)*(sj14));
IKReal x216=((0.0450000000000000)+(x215));
IKReal x217=((0.0450000000000000)*(cj14));
IKReal x218=((x216)+(((-1.00000000000000)*(x217))));
IKReal x219=((0.550000000000000)*(pz));
IKReal x220=((0.0450000000000000)*(cj11)*(px));
IKReal x221=((0.0450000000000000)*(py)*(sj11));
IKReal x222=((0.0450000000000000)*(pz)*(sj14));
IKReal x223=((py)*(sj11)*(x215));
IKReal x224=((cj11)*(px)*(x215));
IKReal x225=((0.300000000000000)*(cj14)*(pz));
IKReal x226=((x219)+(x221)+(x220)+(x223)+(x222)+(x225)+(x224));
IKReal x227=((py)*(sj11)*(x217));
IKReal x228=((cj11)*(px)*(x217));
IKReal x229=((x228)+(x227));
IKReal x230=((x226)+(((-1.00000000000000)*(x229))));
IKReal x231=((IKabs(x230) != 0)?((IKReal)1/(x230)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x231)*(((((-1.00000000000000)*(pz)*(((((py)*(sj11)))+(((cj11)*(px)))))))+(((-1.00000000000000)*(x218)*(((0.550000000000000)+(((0.0450000000000000)*(sj14)))+(((0.300000000000000)*(cj14)))))))))), ((x231)*((((pz)*(pz))+(((-1.00000000000000)*((x218)*(x218))))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x232=((py)*(sj11));
IKReal x233=((cj11)*(px));
IKReal x234=((x232)+(x233));
IKReal x235=((0.300000000000000)*(sj14));
IKReal x236=((0.0450000000000000)+(x235));
IKReal x237=((0.0450000000000000)*(cj14));
IKReal x238=((((-1.00000000000000)*(x237)))+(x236));
IKReal x239=((0.0450000000000000)*(sj14));
IKReal x240=((0.300000000000000)*(cj14));
IKReal x241=((0.550000000000000)+(x239)+(x240));
IKReal x242=x5;
IKReal x243=(sj11)*(sj11);
IKReal x244=(x232)*(x232);
IKReal x245=(pz)*(pz);
IKReal x246=(cj11)*(cj11);
IKReal x247=x4;
IKReal x248=(x233)*(x233);
IKReal x249=((2.00000000000000)*(x232)*(x233));
IKReal x250=((x245)+(x244)+(x249)+(x248));
IKReal x251=((-1.00000000000000)*(x250));
IKReal x252=((IKabs(x251) != 0)?((IKReal)1/(x251)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x252)*(((((x234)*(x241)))+(((pz)*(x238)))))), ((x252)*(((((x234)*(x238)))+(((-1.00000000000000)*(pz)*(x241)))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
IKReal x253=((px)*(sj11));
IKReal x254=((cj11)*(py));
evalcond[0]=((-3.14159265358979)+(IKfmod(((-3.14159265358979)+(j13)+(3.14159265358979)), 6.28318530717959)));
evalcond[1]=((0.396550000000000)+(((0.325950000000000)*(cj14)))+(((0.0765000000000000)*(sj14)))+(((-1.00000000000000)*(pp))));
evalcond[2]=((x254)+(((-1.00000000000000)*(x253))));
evalcond[3]=((x253)+(((-1.00000000000000)*(x254))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x255=((4.26078431372549)*(cj14));
IKReal x256=(sj14)*(sj14);
IKReal x257=((1.20294117647059)*(x256));
IKReal x258=(cj14)*(cj14);
IKReal x259=((1.20294117647059)*(x258));
IKReal x260=((3.98071895424837)+(x259)+(x255)+(x257)+(sj14));
dummyeval[0]=x260;
dummyeval[1]=x260;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*((py)*(py))*((sj11)*(sj11))))+(((-1.00000000000000)*((pz)*(pz))))+(((-2.00000000000000)*(cj11)*(px)*(py)*(sj11)))+(((-1.00000000000000)*((cj11)*(cj11))*((px)*(px)))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[2];
IKReal x261=((cj11)*(cj14)*(px));
IKReal x262=((pz)*(sj14));
IKReal x263=((6.66666666666667)*(cj14)*(pz));
IKReal x264=((12.2222222222222)*(pz));
IKReal x265=((cj14)*(py)*(sj11));
IKReal x266=((x265)+(x264)+(x261)+(x263)+(x262));
IKReal x267=((6.66666666666667)*(py)*(sj11)*(sj14));
IKReal x268=((py)*(sj11));
IKReal x269=((6.66666666666667)*(cj11)*(px)*(sj14));
IKReal x270=((cj11)*(px));
IKReal x271=((x267)+(x269)+(x268)+(x270));
IKReal x272=((x266)+(((-1.00000000000000)*(x271))));
dummyeval[0]=x272;
dummyeval[1]=x272;
if( IKabs(dummyeval[0]) < 0.0000100000000000  || IKabs(dummyeval[1]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x273=((0.300000000000000)*(sj14));
IKReal x274=((0.0450000000000000)+(x273));
IKReal x275=((0.0450000000000000)*(cj14));
IKReal x276=((x274)+(((-1.00000000000000)*(x275))));
IKReal x277=((0.550000000000000)*(pz));
IKReal x278=((py)*(sj11)*(x275));
IKReal x279=((0.0450000000000000)*(pz)*(sj14));
IKReal x280=((cj11)*(px)*(x275));
IKReal x281=((0.300000000000000)*(cj14)*(pz));
IKReal x282=((x277)+(x278)+(x279)+(x281)+(x280));
IKReal x283=((0.0450000000000000)*(cj11)*(px));
IKReal x284=((0.0450000000000000)*(py)*(sj11));
IKReal x285=((py)*(sj11)*(x273));
IKReal x286=((cj11)*(px)*(x273));
IKReal x287=((x286)+(x285)+(x284)+(x283));
IKReal x288=((x282)+(((-1.00000000000000)*(x287))));
IKReal x289=((IKabs(x288) != 0)?((IKReal)1/(x288)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x289)*(((((x276)*(((0.550000000000000)+(((0.0450000000000000)*(sj14)))+(((0.300000000000000)*(cj14)))))))+(((pz)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))))))), ((x289)*(((((-1.00000000000000)*((x276)*(x276))))+((pz)*(pz))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x290=((0.0450000000000000)*(sj14));
IKReal x291=((0.300000000000000)*(cj14));
IKReal x292=((0.550000000000000)+(x290)+(x291));
IKReal x293=((0.300000000000000)*(sj14));
IKReal x294=((0.0450000000000000)+(x293));
IKReal x295=((0.0450000000000000)*(cj14));
IKReal x296=((((-1.00000000000000)*(x295)))+(x294));
IKReal x297=((py)*(sj11));
IKReal x298=((cj11)*(px));
IKReal x299=((x298)+(x297));
IKReal x300=((-1.00000000000000)*(x299));
IKReal x301=x5;
IKReal x302=(sj11)*(sj11);
IKReal x303=(x297)*(x297);
IKReal x304=(pz)*(pz);
IKReal x305=(cj11)*(cj11);
IKReal x306=x4;
IKReal x307=(x298)*(x298);
IKReal x308=((2.00000000000000)*(x297)*(x298));
IKReal x309=((x308)+(x307)+(x304)+(x303));
IKReal x310=((-1.00000000000000)*(x309));
IKReal x311=((IKabs(x310) != 0)?((IKReal)1/(x310)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x311)*(((((-1.00000000000000)*(x292)*(x300)))+(((-1.00000000000000)*(pz)*(x296)))))), ((x311)*(((((-1.00000000000000)*(pz)*(x292)))+(((x296)*(x300)))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x312=((0.0765000000000000)*(sj14));
IKReal x313=(cj14)*(cj14);
IKReal x314=((0.0920250000000000)*(x313));
IKReal x315=(sj14)*(sj14);
IKReal x316=((0.0920250000000000)*(x315));
IKReal x317=((0.325950000000000)*(cj14));
IKReal x318=((0.304525000000000)+(x314)+(x317)+(x316)+(x312));
IKReal x319=((IKabs(x318) != 0)?((IKReal)1/(x318)):(IKReal)1.0e30);
IKReal x320=((py)*(sj11));
IKReal x321=((cj11)*(px));
IKReal x322=((x320)+(x321));
IKReal x323=((0.300000000000000)*(sj14));
IKReal x324=((0.0450000000000000)+(x323));
IKReal x325=((0.0450000000000000)*(cj14));
IKReal x326=((((-1.00000000000000)*(x325)))+(x324));
IKReal x327=((0.0450000000000000)*(sj14));
IKReal x328=((0.300000000000000)*(cj14));
IKReal x329=((0.550000000000000)+(x327)+(x328));
j12array[0]=IKatan2(((x319)*(((((pz)*(x326)))+(((-1.00000000000000)*(x322)*(x329)))))), ((x319)*(((((x322)*(x326)))+(((pz)*(x329)))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}
}
}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x330=((0.0450000000000000)*(sj14));
IKReal x331=((0.300000000000000)*(cj14));
IKReal x332=((0.550000000000000)+(x331)+(x330));
IKReal x333=((0.300000000000000)*(sj14));
IKReal x334=((cj11)*(py)*(sj13));
IKReal x335=((0.0450000000000000)+(x333)+(x334));
IKReal x336=((0.0450000000000000)*(cj14));
IKReal x337=((px)*(sj11)*(sj13));
IKReal x338=((x337)+(x336));
IKReal x339=((x335)+(((-1.00000000000000)*(x338))));
IKReal x340=(pz)*(pz);
IKReal x341=((cj13)*(x340));
IKReal x342=x5;
IKReal x343=(sj11)*(sj11);
IKReal x344=((cj13)*(x342)*(x343));
IKReal x345=(cj11)*(cj11);
IKReal x346=x4;
IKReal x347=((cj13)*(x345)*(x346));
IKReal x348=((2.00000000000000)*(cj11)*(cj13)*(px)*(py)*(sj11));
IKReal x349=((x341)+(x347)+(x344)+(x348));
IKReal x350=((-1.00000000000000)*(x349));
IKReal x351=((IKabs(x350) != 0)?((IKReal)1/(x350)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x351)*(((((x332)*(((((cj13)*(py)*(sj11)))+(((cj11)*(cj13)*(px)))))))+(((pz)*(x339)))))), ((x351)*(((((-1.00000000000000)*(cj13)*(pz)*(x332)))+(((x339)*(((((py)*(sj11)))+(((cj11)*(px)))))))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x352=((0.0450000000000000)*(sj14));
IKReal x353=((0.300000000000000)*(cj14));
IKReal x354=((0.550000000000000)+(x353)+(x352));
IKReal x355=((0.0450000000000000)*(cj13)*(cj14)*(pz));
IKReal x356=((0.550000000000000)*(py)*(sj11));
IKReal x357=((py)*(sj11)*(x353));
IKReal x358=((cj11)*(px)*(x352));
IKReal x359=((py)*(sj11)*(x352));
IKReal x360=((cj11)*(px)*(x353));
IKReal x361=((0.550000000000000)*(cj11)*(px));
IKReal x362=((x355)+(x357)+(x356)+(x359)+(x358)+(x360)+(x361));
IKReal x363=((0.300000000000000)*(cj13)*(pz)*(sj14));
IKReal x364=((0.0450000000000000)*(cj13)*(pz));
IKReal x365=((x363)+(x364));
IKReal x366=((((-1.00000000000000)*(x365)))+(x362));
IKReal x367=((IKabs(x366) != 0)?((IKReal)1/(x366)):(IKReal)1.0e30);
j12array[0]=IKatan2(((x367)*((((pz)*(pz))+(((-1.00000000000000)*((x354)*(x354))))))), ((-1.00000000000000)*(x367)*(((((pz)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))))+(((x354)*(((((0.300000000000000)*(cj13)*(sj14)))+(((0.0450000000000000)*(cj13)))+(((-0.0450000000000000)*(cj13)*(cj14)))))))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}

} else
{
{
IKReal j12array[1], cj12array[1], sj12array[1];
bool j12valid[1]={false};
IKReal x368=((cj11)*(cj13)*(py));
IKReal x369=((cj13)*(px)*(sj11));
IKReal x370=((((-1.00000000000000)*(x369)))+(x368));
IKReal x371=((0.0450000000000000)*(sj14));
IKReal x372=((0.300000000000000)*(cj14));
IKReal x373=((0.550000000000000)+(x372)+(x371));
IKReal x374=(cj11)*(cj11);
IKReal x375=x4;
IKReal x376=((sj13)*(x374)*(x375));
IKReal x377=x5;
IKReal x378=(sj11)*(sj11);
IKReal x379=((sj13)*(x377)*(x378));
IKReal x380=(pz)*(pz);
IKReal x381=((sj13)*(x380));
IKReal x382=((2.00000000000000)*(cj11)*(px)*(py)*(sj11)*(sj13));
IKReal x383=((x382)+(x381)+(x379)+(x376));
IKReal x384=((-1.00000000000000)*(x383));
IKReal x385=((IKabs(x384) != 0)?((IKReal)1/(x384)):(IKReal)1.0e30);
j12array[0]=IKatan2(((-1.00000000000000)*(x385)*(((((pz)*(x370)))+(((x373)*(((((-1.00000000000000)*(cj11)*(px)*(sj13)))+(((-1.00000000000000)*(py)*(sj11)*(sj13)))))))))), ((x385)*(((((-1.00000000000000)*(pz)*(sj13)*(x373)))+(((x370)*(((((-1.00000000000000)*(cj11)*(px)))+(((-1.00000000000000)*(py)*(sj11)))))))))));
sj12array[0]=IKsin(j12array[0]);
cj12array[0]=IKcos(j12array[0]);
if( j12array[0] > IKPI )
{
    j12array[0]-=IK2PI;
}
else if( j12array[0] < -IKPI )
{    j12array[0]+=IK2PI;
}
j12valid[0] = true;
for(int ij12 = 0; ij12 < 1; ++ij12)
{
if( !j12valid[ij12] )
{
    continue;
}
j12 = j12array[ij12]; cj12 = cj12array[ij12]; sj12 = sj12array[ij12];

rotationfunction0(vsolutions);
}
}

}

}
}
}
}
}
}
return vsolutions.size()>0;
}
inline void rotationfunction0(std::vector<IKSolution>& vsolutions) {
for(int rotationiter = 0; rotationiter < 1; ++rotationiter) {
IKReal x45=((sj12)*(sj14));
IKReal x46=((cj12)*(cj13)*(cj14));
IKReal x47=((((-1.00000000000000)*(x46)))+(x45));
IKReal x48=((cj13)*(cj14)*(sj12));
IKReal x49=((cj12)*(sj14));
IKReal x50=((x48)+(x49));
IKReal x51=((-1.00000000000000)*(x50));
IKReal x52=((sj11)*(x47));
IKReal x53=((cj11)*(cj14)*(sj13));
IKReal x54=((x52)+(((-1.00000000000000)*(x53))));
IKReal x55=((cj14)*(sj11)*(sj13));
IKReal x56=((cj11)*(x47));
IKReal x57=((x55)+(x56));
IKReal x58=((cj11)*(cj12)*(sj13));
IKReal x59=((cj13)*(sj11));
IKReal x60=((x59)+(x58));
IKReal x61=((cj12)*(sj11)*(sj13));
IKReal x62=((cj11)*(cj13));
IKReal x63=((x61)+(((-1.00000000000000)*(x62))));
IKReal x64=((cj13)*(x49));
IKReal x65=((cj14)*(sj12));
IKReal x66=((x64)+(x65));
IKReal x67=((-1.00000000000000)*(x66));
IKReal x68=((sj11)*(sj13)*(sj14));
IKReal x69=((cj11)*(x67));
IKReal x70=((x68)+(x69));
IKReal x71=((cj12)*(cj14));
IKReal x72=((cj13)*(x45));
IKReal x73=((((-1.00000000000000)*(x72)))+(x71));
IKReal x74=((sj11)*(x67));
IKReal x75=((cj11)*(sj13)*(sj14));
IKReal x76=((((-1.00000000000000)*(x75)))+(x74));
new_r00=((((r10)*(x54)))+(((r00)*(x57)))+(((r20)*(x51))));
new_r01=((((r11)*(x54)))+(((r01)*(x57)))+(((r21)*(x51))));
new_r02=((((r22)*(x51)))+(((r02)*(x57)))+(((r12)*(((x52)+(((-1.00000000000000)*(x53))))))));
new_r10=((((r10)*(x63)))+(((r00)*(x60)))+(((r20)*(sj12)*(sj13))));
new_r11=((((r11)*(x63)))+(((r01)*(x60)))+(((r21)*(sj12)*(sj13))));
new_r12=((((r22)*(sj12)*(sj13)))+(((r02)*(x60)))+(((r12)*(x63))));
new_r20=((((r10)*(x76)))+(((r20)*(x73)))+(((r00)*(x70))));
new_r21=((((r21)*(x73)))+(((r11)*(x76)))+(((r01)*(x70))));
new_r22=((((r22)*(x73)))+(((r02)*(x70)))+(((r12)*(((((-1.00000000000000)*(x75)))+(x74))))));
{
IKReal j16array[2], cj16array[2], sj16array[2];
bool j16valid[2]={false};
cj16array[0]=new_r22;
if( cj16array[0] >= -1.0001 && cj16array[0] <= 1.0001 )
{
    j16valid[0] = j16valid[1] = true;
    j16array[0] = IKacos(cj16array[0]);
    sj16array[0] = IKsin(j16array[0]);
    cj16array[1] = cj16array[0];
    j16array[1] = -j16array[0];
    sj16array[1] = -sj16array[0];
}
else if( isnan(cj16array[0]) )
{
    // probably any value will work
    j16valid[0] = true;
    cj16array[0] = 1; sj16array[0] = 0; j16array[0] = 0;
}
if( j16valid[0] && j16valid[1] && IKabs(cj16array[0]-cj16array[1]) < 0.0001 && IKabs(sj16array[0]-sj16array[1]) < 0.0001 )
{
    j16valid[1]=false;
}
for(int ij16 = 0; ij16 < 2; ++ij16)
{
if( !j16valid[ij16] )
{
    continue;
}
j16 = j16array[ij16]; cj16 = cj16array[ij16]; sj16 = sj16array[ij16];

{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=(((new_r12)*(new_r12))+((new_r02)*(new_r02)));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((cj16)*((new_r02)*(new_r02))))+(((cj16)*((new_r12)*(new_r12)))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[7];
evalcond[0]=((IKfmod(((-1.57079632679490)+(j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=new_r22;
evalcond[2]=((-1.00000000000000)*(new_r22));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(new_r21, ((-1.00000000000000)*(new_r20)));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
IKReal dummyeval[1];
dummyeval[0]=(((new_r12)*(new_r12))+((new_r02)*(new_r02)));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(new_r02)*(new_r11)))+(((new_r01)*(new_r12))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(new_r02)*(new_r10)))+(((new_r00)*(new_r12))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x77=((new_r02)*(new_r10));
IKReal x78=((new_r00)*(new_r12));
j15array[0]=IKatan2(((new_r00)*(((IKabs(((((-1.00000000000000)*(x77)))+(x78))) != 0)?((IKReal)1/(((((-1.00000000000000)*(x77)))+(x78)))):(IKReal)1.0e30))), ((new_r10)*(((IKabs(((((-1.00000000000000)*(x78)))+(x77))) != 0)?((IKReal)1/(((((-1.00000000000000)*(x78)))+(x77)))):(IKReal)1.0e30))));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x79=((new_r02)*(new_r11));
IKReal x80=((new_r01)*(new_r12));
j15array[0]=IKatan2(((new_r01)*(((IKabs(((((-1.00000000000000)*(x79)))+(x80))) != 0)?((IKReal)1/(((((-1.00000000000000)*(x79)))+(x80)))):(IKReal)1.0e30))), ((new_r11)*(((IKabs(((x79)+(((-1.00000000000000)*(x80))))) != 0)?((IKReal)1/(((x79)+(((-1.00000000000000)*(x80)))))):(IKReal)1.0e30))));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x81=(new_r12)*(new_r12);
IKReal x82=(new_r02)*(new_r02);
IKReal x83=((x82)+(x81));
IKReal x84=((IKabs(x83) != 0)?((IKReal)1/(x83)):(IKReal)1.0e30);
j15array[0]=IKatan2(((new_r12)*(x84)), ((new_r02)*(x84)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}
}
}

} else
{
evalcond[0]=((-3.14159265358979)+(IKfmod(((1.57079632679490)+(j16)+(3.14159265358979)), 6.28318530717959)));
evalcond[1]=new_r22;
evalcond[2]=new_r22;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((-1.00000000000000)*(new_r21)), new_r20);
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
IKReal dummyeval[1];
dummyeval[0]=((((new_r02)*(new_r11)))+(((-1.00000000000000)*(new_r01)*(new_r12))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(new_r00)*(new_r12)))+(((new_r02)*(new_r10))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(new_r00)*(new_r01)))+(((-1.00000000000000)*(new_r10)*(new_r11))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x85=((new_r10)*(new_r11));
IKReal x86=((new_r00)*(new_r01));
IKReal x87=((x86)+(x85));
j15array[0]=IKatan2(((-1.00000000000000)*(new_r01)*(sj17)*(((IKabs(x87) != 0)?((IKReal)1/(x87)):(IKReal)1.0e30))), ((new_r11)*(sj17)*(((IKabs(x87) != 0)?((IKReal)1/(x87)):(IKReal)1.0e30))));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x88=((new_r00)*(new_r12));
IKReal x89=((new_r02)*(new_r10));
j15array[0]=IKatan2(((new_r00)*(((IKabs(((x89)+(((-1.00000000000000)*(x88))))) != 0)?((IKReal)1/(((x89)+(((-1.00000000000000)*(x88)))))):(IKReal)1.0e30))), ((new_r10)*(((IKabs(((x88)+(((-1.00000000000000)*(x89))))) != 0)?((IKReal)1/(((x88)+(((-1.00000000000000)*(x89)))))):(IKReal)1.0e30))));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x90=((new_r01)*(new_r12));
IKReal x91=((new_r02)*(new_r11));
j15array[0]=IKatan2(((new_r01)*(((IKabs(((x91)+(((-1.00000000000000)*(x90))))) != 0)?((IKReal)1/(((x91)+(((-1.00000000000000)*(x90)))))):(IKReal)1.0e30))), ((new_r11)*(((IKabs(((x90)+(((-1.00000000000000)*(x91))))) != 0)?((IKReal)1/(((x90)+(((-1.00000000000000)*(x91)))))):(IKReal)1.0e30))));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}
}
}

} else
{
evalcond[0]=((IKfmod(((j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=((-1.00000000000000)+(new_r22));
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=((-1.00000000000000)*(new_r20));
evalcond[5]=((-1.00000000000000)*(new_r21));
evalcond[6]=((1.00000000000000)+(((-1.00000000000000)*(new_r22))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  )
{
{
IKReal j15array[2], cj15array[2], sj15array[2];
bool j15valid[2]={false};
IKReal x92=IKatan2(new_r02, new_r12);
j15array[0]=((-1.00000000000000)*(x92));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
j15array[1]=((3.14159265358979)+(((-1.00000000000000)*(x92))));
sj15array[1]=IKsin(j15array[1]);
cj15array[1]=IKcos(j15array[1]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
if( j15array[1] > IKPI )
{
    j15array[1]-=IK2PI;
}
else if( j15array[1] < -IKPI )
{    j15array[1]+=IK2PI;
}
j15valid[1] = true;
if( j15valid[0] && j15valid[1] && IKabs(cj15array[0]-cj15array[1]) < 0.0001 && IKabs(sj15array[0]-sj15array[1]) < 0.0001 )
{
    j15valid[1]=false;
}
for(int ij15 = 0; ij15 < 2; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((-1.00000000000000)*(new_r11)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r01)))), ((((cj15)*(new_r00)))+(((new_r10)*(sj15)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}
}
}

} else
{
IKReal x93=((1.00000000000000)+(new_r22));
evalcond[0]=((IKfmod(((-3.14159265358979)+(j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=x93;
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=new_r20;
evalcond[5]=new_r21;
evalcond[6]=x93;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  )
{
{
IKReal j15array[2], cj15array[2], sj15array[2];
bool j15valid[2]={false};
IKReal x94=IKatan2(new_r02, new_r12);
j15array[0]=((-1.00000000000000)*(x94));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
j15array[1]=((3.14159265358979)+(((-1.00000000000000)*(x94))));
sj15array[1]=IKsin(j15array[1]);
cj15array[1]=IKcos(j15array[1]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
if( j15array[1] > IKPI )
{
    j15array[1]-=IK2PI;
}
else if( j15array[1] < -IKPI )
{    j15array[1]+=IK2PI;
}
j15valid[1] = true;
if( j15valid[0] && j15valid[1] && IKabs(cj15array[0]-cj15array[1]) < 0.0001 && IKabs(sj15array[0]-sj15array[1]) < 0.0001 )
{
    j15valid[1]=false;
}
for(int ij15 = 0; ij15 < 2; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((cj15)*(new_r01)))+(((new_r11)*(sj15)))), ((((-1.00000000000000)*(new_r10)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r00)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}
}
}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}
}
}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x95=(new_r02)*(new_r02);
IKReal x96=((cj16)*(x95));
IKReal x97=(new_r12)*(new_r12);
IKReal x98=((cj16)*(x97));
IKReal x99=((x98)+(x96));
IKReal x100=((IKabs(x99) != 0)?((IKReal)1/(x99)):(IKReal)1.0e30);
j15array[0]=IKatan2(((new_r12)*(new_r22)*(sj16)*(x100)), ((new_r02)*(new_r22)*(sj16)*(x100)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[11];
IKReal x101=((cj15)*(new_r12));
IKReal x102=((new_r02)*(sj15));
IKReal x103=((((-1.00000000000000)*(x102)))+(x101));
IKReal x104=((cj15)*(new_r02));
IKReal x105=((new_r12)*(sj15));
IKReal x106=((x104)+(x105));
evalcond[0]=((IKfmod(((j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=((-1.00000000000000)+(new_r22));
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=x103;
evalcond[5]=x103;
evalcond[6]=x106;
evalcond[7]=x106;
evalcond[8]=((-1.00000000000000)*(new_r20));
evalcond[9]=((-1.00000000000000)*(new_r21));
evalcond[10]=((1.00000000000000)+(((-1.00000000000000)*(new_r22))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  && IKabs(evalcond[7]) < 0.0000100000000000  && IKabs(evalcond[8]) < 0.0000100000000000  && IKabs(evalcond[9]) < 0.0000100000000000  && IKabs(evalcond[10]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((-1.00000000000000)*(new_r11)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r01)))), ((((cj15)*(new_r00)))+(((new_r10)*(sj15)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

} else
{
IKReal x107=((cj15)*(new_r12));
IKReal x108=((new_r02)*(sj15));
IKReal x109=((((-1.00000000000000)*(x108)))+(x107));
IKReal x110=((cj15)*(new_r02));
IKReal x111=((new_r12)*(sj15));
IKReal x112=((x111)+(x110));
IKReal x113=((1.00000000000000)+(new_r22));
evalcond[0]=((IKfmod(((-3.14159265358979)+(j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=x113;
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=x109;
evalcond[5]=x109;
evalcond[6]=x112;
evalcond[7]=((-1.00000000000000)*(x112));
evalcond[8]=new_r20;
evalcond[9]=new_r21;
evalcond[10]=x113;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  && IKabs(evalcond[7]) < 0.0000100000000000  && IKabs(evalcond[8]) < 0.0000100000000000  && IKabs(evalcond[9]) < 0.0000100000000000  && IKabs(evalcond[10]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((cj15)*(new_r01)))+(((new_r11)*(sj15)))), ((((-1.00000000000000)*(new_r10)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r00)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
IKReal x114=((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30);
j17array[0]=IKatan2(((new_r21)*(x114)), ((-1.00000000000000)*(new_r20)*(x114)));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((-1.00000000000000)*(new_r00)*(sj15)))+(((cj15)*(new_r10)))), ((-1.00000000000000)*(new_r20)*(((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((new_r21)*(((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30))), ((((cj15)*(new_r11)))+(((-1.00000000000000)*(new_r01)*(sj15)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x115=(new_r12)*(new_r12);
IKReal x116=(new_r02)*(new_r02);
IKReal x117=((x116)+(x115));
IKReal x118=((IKabs(x117) != 0)?((IKReal)1/(x117)):(IKReal)1.0e30);
j15array[0]=IKatan2(((new_r12)*(sj16)*(x118)), ((new_r02)*(sj16)*(x118)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=sj16;
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal evalcond[11];
IKReal x119=((cj15)*(new_r12));
IKReal x120=((new_r02)*(sj15));
IKReal x121=((((-1.00000000000000)*(x120)))+(x119));
IKReal x122=((cj15)*(new_r02));
IKReal x123=((new_r12)*(sj15));
IKReal x124=((x122)+(x123));
evalcond[0]=((IKfmod(((j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=((-1.00000000000000)+(new_r22));
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=x121;
evalcond[5]=x121;
evalcond[6]=x124;
evalcond[7]=x124;
evalcond[8]=((-1.00000000000000)*(new_r20));
evalcond[9]=((-1.00000000000000)*(new_r21));
evalcond[10]=((1.00000000000000)+(((-1.00000000000000)*(new_r22))));
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  && IKabs(evalcond[7]) < 0.0000100000000000  && IKabs(evalcond[8]) < 0.0000100000000000  && IKabs(evalcond[9]) < 0.0000100000000000  && IKabs(evalcond[10]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((-1.00000000000000)*(new_r11)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r01)))), ((((cj15)*(new_r00)))+(((new_r10)*(sj15)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

} else
{
IKReal x125=((cj15)*(new_r12));
IKReal x126=((new_r02)*(sj15));
IKReal x127=((((-1.00000000000000)*(x126)))+(x125));
IKReal x128=((cj15)*(new_r02));
IKReal x129=((new_r12)*(sj15));
IKReal x130=((x128)+(x129));
IKReal x131=((1.00000000000000)+(new_r22));
evalcond[0]=((IKfmod(((-3.14159265358979)+(j16)+(3.14159265358979)), 6.28318530717959))+(-3.14159265358979));
evalcond[1]=x131;
evalcond[2]=new_r20;
evalcond[3]=new_r21;
evalcond[4]=x127;
evalcond[5]=x127;
evalcond[6]=x130;
evalcond[7]=((-1.00000000000000)*(x130));
evalcond[8]=new_r20;
evalcond[9]=new_r21;
evalcond[10]=x131;
if( IKabs(evalcond[0]) < 0.0000100000000000  && IKabs(evalcond[1]) < 0.0000100000000000  && IKabs(evalcond[2]) < 0.0000100000000000  && IKabs(evalcond[3]) < 0.0000100000000000  && IKabs(evalcond[4]) < 0.0000100000000000  && IKabs(evalcond[5]) < 0.0000100000000000  && IKabs(evalcond[6]) < 0.0000100000000000  && IKabs(evalcond[7]) < 0.0000100000000000  && IKabs(evalcond[8]) < 0.0000100000000000  && IKabs(evalcond[9]) < 0.0000100000000000  && IKabs(evalcond[10]) < 0.0000100000000000  )
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((cj15)*(new_r01)))+(((new_r11)*(sj15)))), ((((-1.00000000000000)*(new_r10)*(sj15)))+(((-1.00000000000000)*(cj15)*(new_r00)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}
}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
IKReal x132=((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30);
j17array[0]=IKatan2(((new_r21)*(x132)), ((-1.00000000000000)*(new_r20)*(x132)));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((((-1.00000000000000)*(new_r00)*(sj15)))+(((cj15)*(new_r10)))), ((-1.00000000000000)*(new_r20)*(((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
j17array[0]=IKatan2(((new_r21)*(((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30))), ((((cj15)*(new_r11)))+(((-1.00000000000000)*(new_r01)*(sj15)))));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}
}
}

}

}

} else
{
{
IKReal j17array[1], cj17array[1], sj17array[1];
bool j17valid[1]={false};
IKReal x133=((IKabs(sj16) != 0)?((IKReal)1/(sj16)):(IKReal)1.0e30);
j17array[0]=IKatan2(((new_r21)*(x133)), ((-1.00000000000000)*(new_r20)*(x133)));
sj17array[0]=IKsin(j17array[0]);
cj17array[0]=IKcos(j17array[0]);
if( j17array[0] > IKPI )
{
    j17array[0]-=IK2PI;
}
else if( j17array[0] < -IKPI )
{    j17array[0]+=IK2PI;
}
j17valid[0] = true;
for(int ij17 = 0; ij17 < 1; ++ij17)
{
if( !j17valid[ij17] )
{
    continue;
}
j17 = j17array[ij17]; cj17 = cj17array[ij17]; sj17 = sj17array[ij17];

{
IKReal dummyeval[1];
dummyeval[0]=(((new_r12)*(new_r12))+((new_r02)*(new_r02)));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((-1.00000000000000)*(new_r00)*(new_r12)))+(((new_r02)*(new_r10))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
{
IKReal dummyeval[1];
dummyeval[0]=((((new_r02)*(new_r11)))+(((-1.00000000000000)*(new_r01)*(new_r12))));
if( IKabs(dummyeval[0]) < 0.0000100000000000  )
{
continue;

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x134=((new_r02)*(new_r11));
IKReal x135=((new_r01)*(new_r12));
IKReal x136=((x134)+(((-1.00000000000000)*(x135))));
IKReal x137=((IKabs(x136) != 0)?((IKReal)1/(x136)):(IKReal)1.0e30);
j15array[0]=IKatan2(((cj17)*(new_r12)*(x137)), ((cj17)*(new_r02)*(x137)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x138=((new_r02)*(new_r10));
IKReal x139=((new_r00)*(new_r12));
IKReal x140=((x138)+(((-1.00000000000000)*(x139))));
IKReal x141=((IKabs(x140) != 0)?((IKReal)1/(x140)):(IKReal)1.0e30);
j15array[0]=IKatan2(((new_r12)*(sj17)*(x141)), ((new_r02)*(sj17)*(x141)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}

} else
{
{
IKReal j15array[1], cj15array[1], sj15array[1];
bool j15valid[1]={false};
IKReal x142=(new_r12)*(new_r12);
IKReal x143=(new_r02)*(new_r02);
IKReal x144=((x142)+(x143));
IKReal x145=((IKabs(x144) != 0)?((IKReal)1/(x144)):(IKReal)1.0e30);
j15array[0]=IKatan2(((new_r12)*(sj16)*(x145)), ((new_r02)*(sj16)*(x145)));
sj15array[0]=IKsin(j15array[0]);
cj15array[0]=IKcos(j15array[0]);
if( j15array[0] > IKPI )
{
    j15array[0]-=IK2PI;
}
else if( j15array[0] < -IKPI )
{    j15array[0]+=IK2PI;
}
j15valid[0] = true;
for(int ij15 = 0; ij15 < 1; ++ij15)
{
if( !j15valid[ij15] )
{
    continue;
}
j15 = j15array[ij15]; cj15 = cj15array[ij15]; sj15 = sj15array[ij15];

{
vsolutions.push_back(IKSolution()); IKSolution& solution = vsolutions.back();
solution.basesol.resize(7);
solution.basesol[0].foffset = j11;
solution.basesol[1].foffset = j12;
solution.basesol[2].foffset = j13;
solution.basesol[3].foffset = j14;
solution.basesol[4].foffset = j15;
solution.basesol[5].foffset = j16;
solution.basesol[6].foffset = j17;
solution.vfree.resize(0);
}
}
}

}

}
}
}

}

}
}
}
}
}};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ik(const IKReal* eetrans, const IKReal* eerot, const IKReal* pfree, std::vector<IKSolution>& vsolutions) {
IKSolver solver;
return solver.ik(eetrans,eerot,pfree,vsolutions);
}

IKFAST_API const char* getKinematicsHash() { return "485ebbdb04195b775513d13c5d87fb7a"; }

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv)
{
    if( argc != 12+getNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",getNumFreeParameters());
        return 1;
    }

    std::vector<IKSolution> vsolutions;
    std::vector<IKReal> vfree(getNumFreeParameters());
    IKReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ik(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, vsolutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)vsolutions.size());
    std::vector<IKReal> sol(getNumJoints());
    for(size_t i = 0; i < vsolutions.size(); ++i) {
        printf("sol%d (free=%d): ", (int)i, (int)vsolutions[i].GetFree().size());
        std::vector<IKReal> vsolfree(vsolutions[i].GetFree().size());
        vsolutions[i].GetSolution(&sol[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( size_t j = 0; j < sol.size(); ++j)
            printf("%.15f, ", sol[j]);
        printf("\n");
    }
    return 0;
}

#endif
